site:
  title: Jmix Docs
  start_page: jmix:ROOT:intro.adoc
content:
  sources: 
  - url: ./
    branches: HEAD
    start_path: content
  - url: https://github.com/cuba-platform/frontend.git
    branches: master
    start_path: docs-src/doc-component-repo
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./content/supplemental
asciidoc:
  attributes:
    # start cuba frontend
    manual_platform: 'https://doc.cuba-platform.com/manual-latest'
    manual_restApi: 'https://doc.cuba-platform.com/restapi-7.2'
    manual_studio: 'https://doc.cuba-platform.com/studio'
    manual_studio_frontendUi: 'https://doc.cuba-platform.com/studio/#frontend_ui'
    restApiSwagger: 'http://files.cuba-platform.com/swagger/7.2'
    compositionGuide: 'https://www.cuba-platform.com/guides/data-modelling-composition'
    petclinic: 'https://github.com/cuba-platform/cuba-petclinic'
    antDesign_base: 'https://ant.design'
    npm_frontendGenerator: 'https://www.npmjs.com/package/@cuba-platform/front-generator'
    npm_cubaReactCore: 'https://www.npmjs.com/package/@cuba-platform/react-core'
    npm_cubaReactUi: 'https://www.npmjs.com/package/@cuba-platform/react-ui'
    npm_cubaRestJs: 'https://www.npmjs.com/package/@cuba-platform/rest'
    forum: 'https://www.cuba-platform.com/discuss'
    api_rest: 'link:../api-reference/cuba-rest-js/index.html'
    git_frontendUi: 'https://github.com/cuba-platform/frontend'
    # end cuba frontend
